
#define SERIAL_COMMAND_ALL          0
#define SERIAL_COMMAND_ULTRASOUND   1
#define SERIAL_COMMAND_LIGHT        2
#define SERIAL_COMMAND_PIR          3

#define SERIAL_COMMAND_VOICE_LIGHTSON     0x10
#define SERIAL_COMMAND_VOICE_LIGHTSOFF    0x11
#define SERIAL_COMMAND_VOICE_LIGHTSON1    0x12
#define SERIAL_COMMAND_VOICE_LIGHTSOFF1   0x13
#define SERIAL_COMMAND_VOICE_LIGHTSON2    0x14
#define SERIAL_COMMAND_VOICE_LIGHTSOFF2   0x15
#define SERIAL_COMMAND_VOICE_AUTOMODEON   0x16
#define SERIAL_COMMAND_VOICE_AUTOMODEOFF  0x17
